[package]
name = "temp_tui"
version = "0.0.4"
edition = "2024"
description = "A command-line tool to convert temperatures between Celsius, Fahrenheit and Kelvin."
license = "MIT"
repository = "github.com"

[dependencies]
